[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "musicimporter"
version = "0.1.0"
description = "Import music from a folder to format and import the contents into your music library."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
    { name = "Fenway Powers" }
]

dependencies = []

[project.scripts]
musicinbox = "musicimporter.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
